### ISSUE TITLE
hls+flv能支持吗？

### ISSUE THREAD

**Issue by qwIvan** [waymao/video_stream_test#2]

**Comment by waymao** [comment]
It supports both of them, but not in a perfect way.
Based on the browser's user-agent, the php script renders different pages for different devices.
Take a look at [here](https://github.com/waymao/video_stream_test/blob/master/index.php), where you can find the algorithm used for distinguishing different kinds of devices.

**Comment by qwIvan** [comment]
我的意思是同时使用，一个m3u8文件里面包含了各个flv格式的视频index

**Comment by waymao** [comment]
Apple doesn't seem to have support for FLV in their HLS protocol, nor does mobile safari support HTML5 Media Source Extensions or flash, so it won't possibly work on iOS devices.
It is possible to work on some desktop browsers, but I still can't see the need for this.

**Comment by qwIvan** [comment]
百度网盘用了hls+flv，但只能在flash播放，想找一下有没有好的方案可以在移动端播放。
https://www.v2ex.com/t/344800

**Comment by waymao** [comment]
目前来说iOS不大可能（原生app除外），安卓6.0以上系统自带浏览器或者Chrome也许可以。

**Comment by waymao** [comment]
Problem seems unsolvable at this time.
